Assignments and categories
fontys-asam/back-end pull request #14
Opened 2021-01-11 10:58 UTC by MeesvanStraten

Fixed some problems

2021-01-12 09:18 UTC, waltersajtos commented
Looks good to me but my code is in here as well (:

2021-01-12 17:05 UTC, Ruby77 requested changes
Looks good guys!

2021-01-12 17:05 UTC, Ruby77 commented on Api/Controllers/CategoryController.cs
> +    [Route("[controller]")]
Same here, not the same attribute

2021-01-12 17:05 UTC, Ruby77 commented on Api/Controllers/CategoryController.cs
> +        public void Delete(int id)
Why is this a void? Shouldn't we  return a HTTP status?

2021-01-12 17:05 UTC, Ruby77 commented on Data/Migrations/20210107130909_fixedAssignmentTypes.cs
> +}
Empty migration?

2021-01-13 10:26 UTC, waltersajtos commented on Api/Controllers/CategoryController.cs
> +        public void Delete(int id)
We didn't make the value controller, it think it came from your branch, no?

2021-01-13 14:25 UTC, Ruby77 submitted a review, later dismissed

2021-01-13 14:30 UTC, waltersajtos approved these changes

2021-01-13 14:35 UTC, merged